# Generated by Django 5.2.14 on 2026-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('shoshilinch', 'Shoshilinch'), ('muhim', 'Muhim'), ('oddiy', 'Oddiy'), ('keyinroq', 'Keyinroq')], default='oddiy', max_length=20),
        ),
    ]
